version: '3'
services:
        app:
                build:
                        context:
                        dockerfile: Dockerfile
                container_name: image1
                stdin_open: true
                tty: true
